config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :rewards, only: [] do
      resources :pledges, only: [:create]
    end
  end

  resources :users, except: [:index] do 
    resources :password_resets, only: [:create, :edit, :update]
    collection do
      get 'backed' 
      get 'owned'
    end

  end
  
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', as: :login
  get 'logout' => 'user_sessions#destroy', as: :logout
  get "signup" => "users#new", :as => :signup

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
	belongs_to :reward
	belongs_to :backer, class_name: "User", foreign_key: "backer_id"
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :rewards
	has_many :pledges, through: :rewards
	belongs_to :owner, class_name: "User"
	accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :pledges, :reject_if => :all_blank, :allow_destroy => true

	validates :title, presence: true
	validates :description, presence: true
	validates :goal, presence: true

	scope :active, -> {where('end_date > ?', Time.zone.now)}

	
end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
	has_many :pledges
	has_many :users, through: :pledges
end

app/models/user.rb
class User < ActiveRecord::Base	
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true
  
  has_many :projects, foreign_key: "owner_id"
  has_many :pledges, foreign_key: "backer_id"
  has_many :rewards, through: :pledges 

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
  	redirect_to login_url, alert: "Please login to access this page"
  end

  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  def create
  	@user = User.find_by_email(param[:email])
  	@user.deliver_reset_password_instructions! if @user
  	redirect_to(login_path, :notice => 'Instructions have been sent to your email.')
  end

  def edit
  	@token = params[:id]
  	@user = User.load_from_reset_password_token(params[:id])
  	if @user.blank?
  		not_authenticated
  		return
  	end
  end

  def update
  	@token = params[:id]
  	@user = User.load_from_reset_password_token(params[:id])
  	if @user.blank?
  		not_authenticated
  		return
  	end
		@user.password_confirmation = params[:user][:password_confirmation]
		if @user.change_password!(params[:user][:password])
			redirect_to(login_path, :notice => 'Password was successfully updated.')
		else
			render :action => "edit"
		end
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	def new
	end

	def create
		@pledge = Pledge.new(pledge_params)

		respond_to do |format|
			if @pledge.save
				@project = Project.find(params[:project_id])
				@pledged = @project.pledges.pluck(:amount).sum
				@goal = @project.goal
				@progress = @pledged.to_f / @goal.to_f * 100
				format.html { redirect_to project_path(@pledge.reward.project) }
				format.js {}
			else
				format.html { render 'new' }
				format.js {}
			end
		end
	end

	private
	def pledge_params
		params.require(:pledge).permit(
			:reward_id,
			:backer_id,
			:amount
		)
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	def index
		@projects = Project.active.order('projects.created_at DESC').page(params[:page])
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		@project.owner_id = current_user.id
		# @project = Project.new(project_params)

		if @project.save
			redirect_to project_path(@project.id)
		else 
			render :new
		end
	end
	
	def show
    @project = Project.find(params[:id])
    @pledged = @project.pledges.pluck(:amount).sum
    @goal = @project.goal
    @progress = @pledged.to_f / @goal.to_f * 100
	end

	def update
	end

	def edit
	end

	def destroy
	end

	private
	def project_params
		params.require(:project).permit(:title,
			:description,
			:goal,
			:start_date,
			:end_date,
			rewards_attributes: [
				:description,
				:qty,
				:price
			]
		)
	end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

def index
end

def new
end

def create
end

def edit
end

def show
end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def new
	end

	def create
	end

	def edit
	end

	private 
	def user_params
		params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
	end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	if @user = login(params[:email], params[:password])
  		redirect_back_or_to projects_url, notice: "You are logged in."
  	else
  		flash[:alert] = "Login Failed."
  		@user = User.new(email: params[:email])
  		render action: "new"
  	end
  end

  def destroy
  	logout
  	redirect_to projects_url, notice: "You've been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to projects_path
		else 
			render :new
		end
	end

	def edit
	end

	def show
		@user = User.find(params[:id])
	end

	def owned
		@owned_projects = current_user.projects.sort_by{|project| project.end_date }
		respond_to do |format|
      format.html do
        if request.xhr?
          render 'owned', layout: false
        end
      end
    end
	end

	def backed
		respond_to do |format|
      format.html do
        if request.xhr?
          render 'backed', layout: false
        end
      end
    end
	end

	private 
	def user_params
		params.require(:user).permit(
			:email, 
			:first_name, 
			:last_name, 
			:password, 
			:password_confirmation, 
			:avatar
		)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
  <title>Crowdfunder</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	  <!-- Latest compiled and minified CSS -->
</head>

<body>

	<nav class="navbar navbar-default">	
		<div class="container-fluid">
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="#" class="navbar-brand">Crowdfunder</a>
			</div>

			<div class="collapse navbar-collapse" id="navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="active"><a href="/projects">Projects</a></li>
				</ul>	
				<ul class="nav navbar-nav navbar-right">
					<% if current_user %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
								<%= current_user.first_name %> <%=current_user.last_name%> <span class="caret"></span>
							</a>
							<ul class="dropdown-menu" role="menu">
								<li><%= link_to("My Profile", user_path(current_user.id)) %></li>
								<li><%= link_to("New Project", new_project_path()) %></li>
								<li><%= link_to("Logout", logout_url) %></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to("Signup", new_user_path) %></li>
						<li><%= link_to("Login", :login) %></li>
					<% end %>
				</ul> <!-- navbar-right -->
			</div> <!-- navbar-collapse-1 --> 
		</div> <!-- container-fluid -->
	</nav> <!-- navbar-defaule -->
	
	<div class="container">
		<%= yield %>		
	</div>

</body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/pledges/_pledges_fields.html.erb
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= number_to_currency(reward.price) %></h4>
      </div>
      <div class="modal-body">
        <p><%= reward.description %></p>
      </div>
      <div class="modal-footer">
	      <%= form_for [project, reward, pledge], remote: true do |f| %>
	      	<%= f.hidden_field :backer_id, value: current_user.id %>
          <%= f.hidden_field :amount, value: reward.price %>
          <%= f.hidden_field :reward_id, value: reward.id %>
          <%= f.hidden_field :project_id, value: project.id %>
	      	<%= f.submit "Back this project", class: "btn btn-primary btn-block btn-lrg back-project" %>
	      <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

app/views/pledges/create.js.erb
$('.project-info').html("<%= j(render partial: 'projects/project_info') %>");

$('.reward-info').html("<%= j(render @project.rewards) %>");

$('#reward-modal-<%= @pledge.reward.id %>').modal('hide');
$('body').removeClass('modal-open');

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	<% if @project.errors.any? %>
		<%= render 'shared/error_message', errors: @project.errors %>
	<% end %>
	
	<div class="form-group">
		<%= f.label :title, class: "sr-only" %>
		<%= f.text_field :title, class: "form-control", placeholder: "Title" %>	<br>
		<%= f.label :description, class: "sr-only" %>
		<%= f.text_area :description, class: "form-control", placeholder: "Description" %>
	</div>
	
	<div class="form-group">
		<%= f.label :goal %>
		<div class="input-group">
			<span class="input-group-addon">$</span>
			<%= f.number_field :goal, class: "form-control" %>
		</div>
	</div>
    
  <div class="form-group upload">
      <%= f.label :project_image %>
      <%= f.file_field :avatar %>
  </div>

	<div class="form-group">
		<div class="input-group">
			<%= f.label :start_date%> <br>
			<%= f.datetime_select :start_date, class: "form-control" %>
		</div>
		<div class="input-group">
			<%= f.label :end_date%> <br>
			<%= f.datetime_select :end_date, class: "form-control" %>
		</div>
	</div>
	
	<h3><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Rewards</h3>
	<div class="form-group">
		
		<%= f.fields_for :rewards do |reward| %>
			<%= render 'reward_fields', f: reward %>
		<% end %>
		
		<div class="link">
			<%= link_to_add_association 'Add Reward', f, :rewards, class: "btn btn-primary btn-lg btn-block" %>
		</div>

	</div>
	
	<div class="actions">
		<%= f.submit 'Create Project', class: "btn btn-success btn-lg btn-block" %>
	</div>
<% end %>

app/views/projects/_project_info.html.erb
<div class="col-md-6">
	<ul class="list-group">
		<li id="backer-count" class="list-group-item"> Backers: <span><%= @project.pledges.count %></span> </li>			
		<li id="total-pledged" class="list-group-item"> Pledged: <span><%= number_to_currency(@pledged) %></span> </li>
		<li id="goal" class="list-group-item"> Goal: <%= number_to_currency(@goal) %> </li>
		<li class="list-group-item">
			<div class="progress">
				<div class="progress-bar" role="progressbar" aria-valuenow="<%= @progress %>" aria-valuemin="0" aria-valuemax="100" style=" width: <%= @progress %>%">
					<%= number_to_percentage @progress, precision: 0 %>
				</div>
			</div>
		</li>
	</ul>
</div>

<div class="col-md-6">
	<p id="time-left"><%= ((@project.end_date - Time.zone.now).to_i)/1.day + 1 %> days to go!</p>
	<p>End Date: <%= @project.end_date.strftime("%B %d, %Y") %> </p>
	<p>Project started: <%= @project.start_date.strftime("%B %d, %Y") %></p>
	<p>Description: <%= @project.description %> </p>			
</div>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields well">
  <div class="form-group">
    <%= f.label :price %>
    <div class="input-group">
      <span class="input-group-addon">$</span>
      <%= f.number_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Quantity" %>
    <%= f.number_field :qty, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <%= link_to_remove_association "Remove Reward", f, class: "btn btn-danger" %>
</div>

app/views/projects/index.html.erb
<br>

<h4><%= page_entries_info @projects %></h4>
<% @projects.each do |project| %>
	<div class="well">
		<h2> <%= link_to project.title, project_path(project)	 %> </h2>
		<p> Goal: <%= number_to_currency(project.goal) %> </p>
		<p> Days to go: <%= ((project.end_date - Time.zone.now).to_i)/1.day + 1 %> </p>
		<p> Ending on: <%= project.end_date.strftime("%b %d, %Y") %> </p>
		<p> Description: <%= project.description %> </p>
	</div>
<% end %>

<%= paginate @projects, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered" %>

app/views/projects/new.html.erb
<div class="row col-md-6 col-md-offset-3">

	<h2>New Project</h2>

	<%= render 'form' %>

</div>

app/views/projects/show.html.erb
<div class="jumbotron">
	<h1><%= @project.title %> <small>by: <%= "#{@project.owner.first_name} #{@project.owner.last_name}"%> </small></h1>
</div>
	
<div class="project-info">
	<%= render partial: 'project_info' %>
</div>

<h3>Rewards</h3>

<div class="reward-info">
	<%= render @project.rewards %>
</div>

app/views/rewards/_reward.html.erb
<div class="col-md-6">
	<div class="panel panel-default">
		
		<div class="panel-heading">
			<h5 class="panel-title"> Pledge <%= number_to_currency(reward.price) %> or more </h5>
		</div>
		
		<div class="panel-body">
			<p> Description: <%= reward.description %> </p>
			<p>	Quantity: <%= reward.qty %> </p>
			<p id="reward-backer-count"> Backers: <span><%= reward.pledges.count %></span> </p>
			<p> Remaining: <%= reward.qty - reward.pledges.count %> </p>
		</div>
		
		<% if current_user %>
			<button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#show-reward-modal-<%= reward.id %>">Back this project!</button>
		<% else %>
			<%= link_to "Log In to Back", login_path, class: "btn btn-primary btn-block" %>
		<% end %>

	</div>

	<% if current_user %>
		
		<div id="show-reward-modal-<%= reward.id %>" class="reward-modal modal fade" tabindex="-1" role="dialog" aria-abelliedby="rewardModalLabel" aria-hidden="true">
		 	<%= render partial: 'pledges/pledges_fields', locals: { project: @project, reward: reward, pledge: reward.pledges.new }%>
	 	</div>
	
	<% end %>

</div>

app/views/shared/_error_message.html.erb
<div id="error-message" class="well text-danger">
	<p><%= pluralize errors.count, "error" %> probibited this form from being submitted.</p>

	<ul>
		<% errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
	</ul>

</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="row col-md-4 col-md-offset-4">
	<h1>Log in</h1>

	<%=form_tag user_sessions_path, :method => :post do %>
		<div class="form-group">
			<%= label_tag :email %>
			<%= text_field_tag :email, nil, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= label_tag :password %>
			<%= password_field_tag :password, nil, class: "form-control" %>
		</div>
		<div class="actions">
			<%= submit_tag "Log in"%>
		</div>
	<% end %>
</div>

app/views/users/_owned_projects.html.erb
<div class= "">
	<dl>
		<h2>Owned Projects</h2>
		<p>Total Owned Projects: <%=current_user.projects.count %> </p>
		<% @owned_projects.each do |project| %>
			<div class="well well-sm">
				<dt class="h3"> <%= link_to project.title, project_path(project.id)%> </dt>
					<dd>Description: <%= project.description %>></dd>
					<dd>Days to go: <%= ((project.end_date - Time.zone.now).to_i)/1.day + 1 %> </dd>
					<dd>End Date: <%= project.end_date.strftime("%B %d, %Y") %> </dd>
					<dd>Pledged: <%= number_to_currency(project.pledges.pluck(:amount).sum) %> of <%= number_to_currency(project.goal) %> </dd>
			</div>
		<% end %>
	</dl>
</div>

app/views/users/_pledge.html.erb
<div class= "">
	<dl>
		<h2>Backed Projects</h2>
		<p>Total Projects Backed: <%= current_user.pledges.count %> </p>
		<p>Total Amount Pledged: <%= number_to_currency(current_user.pledges.pluck(:amount).sum) %> </p>

		<% current_user.pledges.each do |pledge| %>
			<div class="well well-sm">
				<dt class="h3"><%= link_to pledge.reward.project.title, project_path(pledge.reward.project)%></dt>
					<dd>Pledge amount:	<%= number_to_currency(pledge.amount) %></dd>
					<dd>Reward Description: <%= pledge.reward.description%></dd>
			</div>
		<% end %>
	</dl>
</div>

app/views/users/backed.html.erb
<%= render partial: 'pledge' %>

app/views/users/new.html.erb
<div class="row col-md-4 col-md-offset-4">

  <h1>Sign Up</h1>

  <%= form_for @user do |f| %>
     <% if @user.errors.any?  %>
      <%= render 'shared/error_message', errors: @user.errors %>
    <% end %>
        
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control"%>
    </div>

    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control"%>
    </div>
    
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control"%>
    </div>
    
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control"%>
    </div>

    <div class="form-group upload">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div class="action"><%= f.submit %></div>
  <% end %>
  
</div>

app/views/users/owned.html.erb
<%= render partial: 'owned_projects' %>

app/views/users/show.html.erb
<div class = "page-header">
	<h2><%= @user.first_name %> <%= @user.last_name %>'s Profile</h2>
</div>

<div class="col-md-4">
	<% if image_tag @user.avatar_url(:medium)%>

		<%=  image_tag @user.avatar_url(:medium), class: 'img-circle' %>
	<% else %>
	<img src="http://fillmurray.com/300/300" alt="">
	<% end %>
</div>

<div class="col-md-8">
	<ul class="nav nav-tabs">
	  <li role="presentation" class="active backed-projects"><a>Backed Projects</a></li>
	  <li role="presentation" class="owned-projects"><a>Owned Projects</a></li>
	</ul>
	<div id="projects-container">
		<%= render partial: "pledge" %> 
	</div>
</div>